<div id="header">

				<div class="top">

					<!-- Logo -->
						<div id="logo">
							<span class="image avatar48"><img src="http://dsi-tools.com/images/etienne-reloaded.png" alt="" /></span>
							<h1 id="title">Etienne</h1>
							<p>PHP5 / MySQL5 / Zend 1.12.13 / Jquery </p>
							<p><a href="/product/restore">RESTAURER LA CONFIGURATION</a></p>
						</div>

					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li><a href="#top" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-home">Liste de course</span></a></li>
								<li><a href="#edition" id="edition-link" class="skel-layers-ignoreHref"><span class="icon fa-th">Edition</span></a></li>
							</ul>
						</nav>

				</div>

				<div class="bottom">



				</div>

			</div>
